<?php

namespace AppBundle\Command\Mail;

use AppBundle\Entity\Common\ThreeSecrets;
use AppBundle\Entity\CommonQuestion;
use AppBundle\Entity\Day;
use AppBundle\Entity\Feedback;
use AppBundle\Entity\Post;
use AppBundle\Entity\Product;
use Doctrine\ORM\EntityManager;
use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputArgument;
use AppBundle\Entity\User;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\VarDumper\VarDumper;

class SendChangesWithoutAlcohol extends ContainerAwareCommand
{

    /** @var EntityManager $em */
    private $em;

    protected function configure()
    {
        $this->setName('app:send-changes-without-alcohol')
            ->setDescription('Send Letter with Day Information')
            ->setHelp('Send Letter with Day Information...');

    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->em = $this->getContainer()->get('doctrine')->getManager();
        $mailer = $this->getContainer()->get('helpers.mailer');
        $users = $users = $this->em->getRepository(ThreeSecrets::class)->findAll();
        $siteUrl = $this->getContainer()->getParameter('site_url');

        $content = $view = $this->getContainer()->get('twig')->render('mail/changes_without_alcohol.html.twig', [
            'confUrl' => $siteUrl . $this->generateUrl('company_page', ['slug' => 'politika-konfidentsialnosti']),
            'siteUrl' => $siteUrl
        ]);


        $currentDate = (int)(new \DateTime())->format('d');
        $subject = 'Что будет происходить с организмом, если не пить алкоголь 28 дней';

        foreach ($users as $user) {
            $day = (int) $user->getCreated()->format('d');
            $diff = date_diff(new \DateTime(), $user->getCreated());

            if ($currentDate - $day == 1 && $diff->days <= 2) {
                $mailer->send($subject, $user->getEmail(), $content);
            }
        }

        $this->forceSendEmail();


        echo 'Letters was sended', PHP_EOL;
        die;
    }

    protected function getContainer()
    {
        return parent::getContainer(); // TODO: Change the autogenerated stub
    }

    protected function generateUrl($route, $parameters = array(), $referenceType = UrlGeneratorInterface::ABSOLUTE_PATH)
    {
        return $this->getContainer()->get('router')->generate($route, $parameters, $referenceType);
    }

    public function forceSendEmail()
    {
        $mailer = $this->getContainer()->get('mailer');
        $spool = $mailer->getTransport()->getSpool();
        $transport = $this->getContainer()->get('swiftmailer.transport.real');
        $spool->flushQueue($transport);
    }


}